import React, { useState } from "react";
import Home from "./pages/Home.jsx";
import Dashboard from "./pages/Dashboard.jsx";

export default function App() {
  const [tab, setTab] = useState("query");

  return (
    <div className="app-shell">
      <div className="top-bar">
        <h1>Evidence-Grounded Clinical RAG - Research Prototype</h1>
        <div className="nav-tabs">
          <button className={tab === "query" ? "active" : ""} onClick={() => setTab("query")}>Query</button>
          <button className={tab === "dashboard" ? "active" : ""} onClick={() => setTab("dashboard")}>Research Dashboard</button>
        </div>
      </div>
      <div className="disclaimer-banner">
        ⚠ Research/demo prototype only - NOT a medical device. All patient data is synthetic.
        Answers are generated by an AI model and independently verified against retrieved evidence,
        but may still be incomplete or wrong. Do not use for real clinical decisions.
      </div>
      {tab === "query" ? <Home /> : <Dashboard />}
    </div>
  );
}
